### ISSUE TITLE
failing to insert features to postgis

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/sar2watermask#23]
> 
> Warning 1: Geometry to be inserted is of type Polygon, whereas the layer geometry type is Multi Polygon.
> Insertion is likely to fail
> ERROR 1: ERROR:  Geometry type (Polygon) does not match column type (MultiPolygon)
> 
> ERROR 1: INSERT command for new feature failed.
> ERROR:  Geometry type (Polygon) does not match column type (MultiPolygon)
> 
> Command: INSERT INTO "masks" ("geom" , "ingestion_time", "area", "id_cogerh") VALUES ('0103000020E6100000010000001F000000F57ED405E10D43C0E0E7B86C641917C00AB683DAE90D43C01BB8B485931917C00AB683DAE90D43C06F702E2BDA1917C00E30A3BDEF0D43C07C702E2BDA1917C00E30A3BDEF0D43C00AF9A3E94F1A17C012AAC2A0F50D43C014F9A3E94F1A17C012AAC2A0F50D43C042C99F027F1A17C027E17175FE0D43C082999B1BAE1A17C027E17175FE0D43C0152211DA231B17C045C9EF01160E43C01C2211DA231B17C04C009FD61E0E43C076DA8A7F6A1B17C04C009FD61E0E43C0F27A82B1C81B17C0350C6010130E43C00B63003EE01B17C02ED5B03B0A0E43C0E2920425B11B17C02ED5B03B0A0E43C08CC2080C821B17C0299E0167010E43C0B7AA8698991B17C027E17175FE0D43C057F20CF3521B17C00FED32AFF20D43C09BC2080C821B17C00AB683DAE90D43C01F2211DA231B17C00C7313CCEC0D43C09D8119A8C51A17C0F57ED405E10D43C07A999B1BAE1A17C0F57ED405E10D43C033E12176671A17C0E810765CCF0D43C048C99F027F1A17C0E653E66ACC0D43C008F9A3E94F1A17C0D21C3796C30D43C023E12176671A17C0C76B68DEB40D43C0CE28A8D0201A17C0CAE587C1BA0D43C0F7CF36F97B1917C0D4D9C687C60D43C0F7CF36F97B1917C0D4D9C687C60D43C035A03212AB1917C0E9CD054ED20D43C05288B09EC21917C0F57ED405E10D43C0E0E7B86C641917C0'::GEOMETRY, '2018/02/04 08:09:35', 29635.33367, 11414) RETURNING "id"
> ERROR 1: Unable to write feature 0 from layer latest.
> ERROR 1: Terminating translation prematurely after failed
> translation of layer latest (use -skipfailures to skip errors)
>

**Comment by schuem** [comment]
Try to cast the polygons to multipolygons: INSERT INTO 'masks' (ST_MULTI('geom', ...
see https://gis.stackexchange.com/questions/14203/how-to-convert-typecast-from-polygon-to-multipolygon-in-postgis

**Comment by jmigueldelgado** [comment]
yes, I did that with python. I think it solved the problem.
